/**
 *
 * Do not edit this file
 *
 */
import { createStore, applyMiddleware } from "redux";
import reducer from "./reducer";
import enforceImmutableState from 'redux-immutable-state-invariant';

export default createStore(reducer, applyMiddleware(enforceImmutableState());
